version: "3"
services:
  trainer:
    image: trainer
    container_name: trainer
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
    environment:
      - MUJOCO_GL=egl
    volumes: 
      - ./trainer:/project/trainer
      - ./scripts:/project/scripts
      - ./logdir:/project/logdir