study:
  storage:
      type: ssh
      host: ${oc.env:SSH_HOST}
      username: ${oc.env:SSH_USERNAME}
      password: ${oc.env:SSH_PASSWORD}
      root_dir: ${oc.env:SSH_DIR}/${..name}
      overwrite: false
  database:
      type: mysql
      name: ${..name} 
      host: ${oc.env:MYSQL_HOST}
      username: ${oc.env:MYSQL_USERNAME}
      password: ${oc.env:MYSQL_PASSWORD}
  metrics: 
      loss:
        name: loss
trainer:
  project: ${..project.project}
  module_path: examples.encoder.modules.SimpleEncoderTrainer
  num_epochs: 1_000_000
  terminal_display: rich
  eval_freq: 20
  batch_size: 400
  save_checkpoint_freq: 1_000_000
  metrics: 
      loss:
        name: loss
      model_weights:
        name: model_weights
  evaluator:
    module_path: examples.encoder.modules.SimpleSupervisedEvaluator
    batch_size: 400
    async_eval: false
    metrics: 
        loss:
          name: loss
  storage:
    input:
      type: ssh
      root_dir: ${....study.storage.root_dir}
      sub_dir: train
      host: ${oc.env:SSH_HOST}
      username: ${oc.env:SSH_USERNAME}
      password: ${oc.env:SSH_PASSWORD}
    output:
      type: ssh
      root_dir: ${....study.storage.root_dir}
      sub_dir: train
      host: ${oc.env:SSH_HOST}
      username: ${oc.env:SSH_USERNAME}
      password: ${oc.env:SSH_PASSWORD}
model:
  project: ${..project.project}
  module_path: examples.encoder.modules.SimpleEncoderModel
  ortho_loss_reg: 0.01
  input_dim: 2
  hidden_dim: 16
  grid_size: 20
  encoder_dim: 8
  loss_type: neuralef
  bandwidth: 1.0
  optimizer:
    name: Adam
    optimizer_kwargs: {
      lr: 0.001
      }
logger:
  project: ${..project.project}
  module_path: trainer.logger.Logger
  sw: wandb
  dir: ${oc.env:LOG_DIR}
  tracked_params: ${model}
  num_epochs: ${..trainer.num_epochs}
  # num_train_steps: ${..trainer.num_train_steps}
  eval_freq: ${..trainer.eval_freq}
  cleanup: true # delete logdir after training
  log_freq: 100_000 # epochs
sweeper:
  project: ${..project.project}
  method: grid
  sweeper_type: wandb
  name: ???
  load_runs_from_queue: true
  heartbeat_timeout: 5
  parameters: ???